name: Node.js CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Build the Docker image based on your Dockerfile
    - name: Build Docker Image
      run: docker build -t my-node-app .

    # Run the application inside the built Docker container
    - name: Run Application Inside Docker
      run: |
        docker run --name my-node-container -d my-node-app
        docker exec my-node-container node /usr/src/app/index.js
