name: Node.js CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Pull Docker Image
      run: docker pull node:14

    - name: Run Application Inside Docker
      run: |
        docker run --name my-node-container -d node:14
        docker cp . my-node-container:/app
        docker exec my-node-container node /app/index.js
